### ISSUE TITLE
Would avoid MD5 as it is an outdated, insecure hash algorithm

### ISSUE THREAD

**Issue by jimbrig** [jbryer/login#4]
I would not suggest using MD5 as your primary hashing algorithm (see https://docs.datadoghq.com/code_analysis/static_analysis_rules/go-security/import-md5/ for example). Would recommend using another cryptographic hashing algorithm family such as `SHA-2`, `SHA-3`, or `HMAC`.

**Comment by jbryer** [comment]
MD5 is not the main hashing algorithm. As the documentation indicates you can use much stronger hashing algorithms for storing passwords and even includes salting. The documentation also indicates that users should use https with their Shiny server. MD5 is only used as an additional layer to ensure the password is not in the clear within memory within the Shiny server. If you can point to other JavaScript libraries that don't add additional overhead or requirements (i.e. specific versions of a browser) I can integrate those.

**Comment by jimbrig** [comment]
@jbryer gotcha, that's what I figured and makes perfect sense given HTTPS is assumed, I'm just not used to seeing MD5 anywhere anymore is all.

Regarding implementing other options I can provide you with these resources which would all be straightforward to implement in a similar fashion as the md5 implementation:
- [chrisveness/crypto](https://github.com/chrisveness/crypto/tree/master)
- [SubtleCrypto: digest() method | MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) (see also: [this gist](https://gist.github.com/chrisveness/e5a07769d06ed02a2587df16742d3fdd))
- [bcrypt | npm](https://www.npmjs.com/package/bcrypt)
- [scrypt | npm](https://www.npmjs.com/package/scrypt)

***

PS: I have been working on developing a custom authentication and user management service / platform specific to Shiny using plumber and this project caught my eye. Great work!
